### ISSUE TITLE
coc-settings.json not respected in absence of local prettier config

### ISSUE THREAD

**Issue by avahe-kellenberger** [neoclide/coc-prettier#28]
If a project does not have a prettier configuration file, the settings in `coc-settings.json` for prettier are not used. Here is my sample coc-settings.json:

```jsonc
{
  "coc.preferences.formatOnSaveFiletypes": [
      "javascript",
      "typescript"
    ],
  "prettier.semi": false
}
```

In file types `javascript` and `typescript`, semicolons are automatically added when formatted with Prettier (unless I create a prettier config file local to the project).

**Comment by chemzqm** [comment]
Should be fixed on latest release of coc.nvim.

**Comment by tuxflo** [comment]
I'm facing the same problem and it seems that this isn't fixed, at least not in the current version:
```
## versions

vim version: NVIM v0.4.3
node version: v14.3.0
coc.nvim version: 0.0.78-c250e18604
coc.nvim directory: /home/fhennig/.vim/plugged/coc.nvim
term: xterm-kitty
platform: linux
```

**Comment by Lakshamana** [comment]
It seems like `coc-prettier`'s default rules are being enforced when local prettier config is not present

**Comment by chakrihacker** [comment]
Any update on this?

**Comment by chemzqm** [comment]
Workspace configuration resolve should be fixed on coc.nvim, try start vim in workspace directory to see if it helps.

**Comment by chemzqm** [comment]
You might have `.editorconfig` in the parent folder, so that configuration is ignored, make sure check the output.
