### ISSUE TITLE
prettier incorrectly reports error after breaking & then fixing syntax in JSON

### ISSUE THREAD

**Issue by ctaylo21** [neoclide/coc-prettier#3]
I've noticed that after I edit a .json file and make it invalid, then fix the bug so the .json is valid again, I get weird behavior from `coc-prettier`. It appears to print an error after I've fixed the json file, almost like it's printing results from the last action, as it also prints a successful `formatted by prettier` message after I've broken the json file.

### Steps to Reproduce
1. Install coc.nvim and coc-prettier
2. Enable `  "coc.preferences.formatOnSaveFiletypes": ["json"]` in `coc-settings.json`
3. Edit valid `json` file (I just used project `package.json` file) and remove comma after one entry (making it invalid json) and save.
4. Message `[coc.nvim] Formatted by prettier` appears in message line
5. Add comma back so json is valid, and save again. Now the message `[coc.nvim] languageserver error on willSaveUntil Unexpected string in JSON at position 150 while parsing '{ "name": "random", "test' in package.json` is output in red in message line even though JSON is valid

### Details
1. `coc.nvim` version - 0.0.61

### Example
![coc-prettier-bug](https://user-images.githubusercontent.com/1427469/54697616-1a44d780-4aeb-11e9-8400-b8ee16882b21.gif)

**Comment by chemzqm** [comment]
Fixed.

**Comment by ctaylo21** [comment]
@chemzqm Thanks for quick turnaround!  I still see this error after running `:CocUpdate`. Do I need to install from master branch to see fixes?

**Comment by chemzqm** [comment]
Need build coc.nvim from master.
