### ISSUE TITLE
Plugin update error

### ISSUE THREAD

**Issue by kostiskalkounos** [neoclide/coc-prettier#96]
After the latest commit I tried to update and I got the following error.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/27889580/97288567-4a676700-1846-11eb-97ab-cd4a86352b3d.png">

Thoughts?

**Comment by chemzqm** [comment]
Fixed on latest release branch of coc.nvim.

**Comment by Jestar342** [comment]
I'm still seeing this error when `:CocInstall coc-prettier` after upgrade to coc.nvim v0.79
