### ISSUE TITLE
"Could not resolve dependency" when installation

### ISSUE THREAD

**Issue by Luffbee** [neoclide/coc-prettier#98]
![image](https://user-images.githubusercontent.com/17215435/98922523-86b8e980-250d-11eb-942c-1a715c31a7b7.png)

**Comment by chemzqm** [comment]
Was fixed on latest release branch of coc.nvim.

**Comment by paraduxos** [comment]
I still have this issue

```md
OS: Windows 10
NVIM v0.5.0-dev+992-gf3a8c930a
coc.nvim version: 0.0.80-a112e6621b
```
<details><summary>coc log</summary>

```bash
2021-01-09T16:16:59.461 INFO (pid:1860) [model-installer] - npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: coc-prettier@1.1.20
npm ERR! Found: prettier@2.2.1
npm ERR! node_modules/prettier
npm ERR!   prettier@"^2.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer prettier@"^1.7.4" from prettier-tslint@0.4.2
npm ERR! node_modules/prettier-tslint
npm ERR!   prettier-tslint@"^0.4.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See <MYPATH>\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     <MYPATH>\2021-01-09T09_16_59_441Z-debug.log

2021-01-09T16:16:59.461 ERROR (pid:1860) [extensions] - Error on install coc-prettier Error: C:\Program Files\nodejs\npm.CMD install exited with 1
    at ChildProcess.<anonymous> (<MYPATH>\AppData\Local\nvim\autoload\plugged\coc.nvim\build\index.js:205:12549)
    at ChildProcess.emit (node:events:376:20)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
```
</details>

<details><summary>eresolve-report.txt</summary>

```bash
# npm resolution error report

2021-01-09T09:16:59.439Z

While resolving: coc-prettier@1.1.20
Found: prettier@2.2.1
node_modules/prettier
  prettier@"^2.1.2" from the root project

Could not resolve dependency:
peer prettier@"^1.7.4" from prettier-tslint@0.4.2
node_modules/prettier-tslint
  prettier-tslint@"^0.4.2" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "prettier",
    "version": "2.2.1",
    "whileInstalling": {
      "name": "coc-prettier",
      "version": "1.1.20",
      "path": "C:\\Users\\PARADU~1\\AppData\\Local\\Temp\\coc-prettier-mfWmq1"
    },
    "location": "node_modules/prettier",
    "dependents": [
      {
        "type": "prod",
        "name": "prettier",
        "spec": "^2.1.2",
        "from": {
          "location": "C:\\Users\\PARADU~1\\AppData\\Local\\Temp\\coc-prettier-mfWmq1"
        }
      }
    ]
  },
  "edge": {
    "type": "peer",
    "name": "prettier",
    "spec": "^1.7.4",
    "error": "INVALID",
    "from": {
      "name": "prettier-tslint",
      "version": "0.4.2",
      "whileInstalling": {
        "name": "coc-prettier",
        "version": "1.1.20",
        "path": "C:\\Users\\PARADU~1\\AppData\\Local\\Temp\\coc-prettier-mfWmq1"
      },
      "location": "node_modules/prettier-tslint",
      "dependents": [
        {
          "type": "prod",
          "name": "prettier-tslint",
          "spec": "^0.4.2",
          "from": {
            "location": "C:\\Users\\PARADU~1\\AppData\\Local\\Temp\\coc-prettier-mfWmq1"
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}
```
</details>

<details><summary>debug.log</summary>

```bash
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '--ignore-scripts',
0 verbose cli   '--no-lockfile',
0 verbose cli   '--production'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.1
# Skip 3 - 24
25 silly idealTree buildDeps
26 silly fetch manifest core-js@^3.6.5
27 http fetch GET 304 https://registry.npmjs.org/core-js 252ms (from cache)
28 silly fetch manifest prettier@^2.1.2
29 http fetch GET 304 https://registry.npmjs.org/prettier 67ms (from cache)
30 silly fetch manifest prettier-eslint@^11.0.0
31 http fetch GET 304 https://registry.npmjs.org/prettier-eslint 99ms (from cache)
32 silly fetch manifest prettier-stylelint@^0.4.2
33 http fetch GET 304 https://registry.npmjs.org/prettier-stylelint 67ms (from cache)
34 silly fetch manifest prettier-tslint@^0.4.2
35 http fetch GET 304 https://registry.npmjs.org/prettier-tslint 70ms (from cache)
36 timing idealTree Completed in 593ms
37 timing command:install Completed in 595ms
38 verbose stack Error: unable to resolve dependency tree
38 verbose stack     at Arborist.[failPeerConflict] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1061:25)
38 verbose stack     at Arborist.[loadPeerSet] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1041:36)
38 verbose stack     at async Arborist.[buildDepStep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:796:11)
38 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:209:7)
38 verbose stack     at async Promise.all (index 1)
38 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:123:5)
38 verbose stack     at async install (C:\Program Files\nodejs\node_modules\npm\lib\install.js:38:3)
39 verbose cwd <MYPATH>\AppData\Local\Temp\coc-prettier-mfWmq1
40 verbose Windows_NT 10.0.18363
41 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--ignore-scripts" "--no-lockfile" "--production"
42 verbose node v15.5.1
43 verbose npm  v7.3.0
44 error code ERESOLVE
45 error ERESOLVE unable to resolve dependency tree
46 error
47 error While resolving: coc-prettier@1.1.20
47 error Found: prettier@2.2.1
47 error node_modules/prettier
47 error   prettier@"^2.1.2" from the root project
47 error
47 error Could not resolve dependency:
47 error peer prettier@"^1.7.4" from prettier-tslint@0.4.2
47 error node_modules/prettier-tslint
47 error   prettier-tslint@"^0.4.2" from the root project
47 error
47 error Fix the upstream dependency conflict, or retry
47 error this command with --force, or --legacy-peer-deps
47 error to accept an incorrect (and potentially broken) dependency resolution.
47 error
47 error See <MYPATH>\Local\npm-cache\eresolve-report.txt for a full report.
48 verbose exit 1
```
</details>

**Comment by paraduxos** [comment]
I still have this issue

```md
OS: Windows 10
NVIM v0.5.0-dev+992-gf3a8c930a
coc.nvim version: 0.0.80-a112e6621b
```
<details><summary>coc log</summary>

```bash
2021-01-09T16:16:59.461 INFO (pid:1860) [model-installer] - npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: coc-prettier@1.1.20
npm ERR! Found: prettier@2.2.1
npm ERR! node_modules/prettier
npm ERR!   prettier@"^2.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer prettier@"^1.7.4" from prettier-tslint@0.4.2
npm ERR! node_modules/prettier-tslint
npm ERR!   prettier-tslint@"^0.4.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See <MYPATH>\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     <MYPATH>\2021-01-09T09_16_59_441Z-debug.log

2021-01-09T16:16:59.461 ERROR (pid:1860) [extensions] - Error on install coc-prettier Error: C:\Program Files\nodejs\npm.CMD install exited with 1
    at ChildProcess.<anonymous> (<MYPATH>\AppData\Local\nvim\autoload\plugged\coc.nvim\build\index.js:205:12549)
    at ChildProcess.emit (node:events:376:20)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
```
</details>

<details><summary>eresolve-report.txt</summary>

```bash
# npm resolution error report

2021-01-09T09:16:59.439Z

While resolving: coc-prettier@1.1.20
Found: prettier@2.2.1
node_modules/prettier
  prettier@"^2.1.2" from the root project

Could not resolve dependency:
peer prettier@"^1.7.4" from prettier-tslint@0.4.2
node_modules/prettier-tslint
  prettier-tslint@"^0.4.2" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "prettier",
    "version": "2.2.1",
    "whileInstalling": {
      "name": "coc-prettier",
      "version": "1.1.20",
      "path": "C:\\Users\\<MYPATH>\\AppData\\Local\\Temp\\coc-prettier-mfWmq1"
    },
    "location": "node_modules/prettier",
    "dependents": [
      {
        "type": "prod",
        "name": "prettier",
        "spec": "^2.1.2",
        "from": {
          "location": "C:\\Users\\<MYPATH>\\AppData\\Local\\Temp\\coc-prettier-mfWmq1"
        }
      }
    ]
  },
  "edge": {
    "type": "peer",
    "name": "prettier",
    "spec": "^1.7.4",
    "error": "INVALID",
    "from": {
      "name": "prettier-tslint",
      "version": "0.4.2",
      "whileInstalling": {
        "name": "coc-prettier",
        "version": "1.1.20",
        "path": "C:\\Users\\<MYPATH>\\AppData\\Local\\Temp\\coc-prettier-mfWmq1"
      },
      "location": "node_modules/prettier-tslint",
      "dependents": [
        {
          "type": "prod",
          "name": "prettier-tslint",
          "spec": "^0.4.2",
          "from": {
            "location": "C:\\Users\\<MYPATH>\\AppData\\Local\\Temp\\coc-prettier-mfWmq1"
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}
```
</details>

<details><summary>debug.log</summary>

```bash
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '--ignore-scripts',
0 verbose cli   '--no-lockfile',
0 verbose cli   '--production'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.1
# Skip 3 - 24
25 silly idealTree buildDeps
26 silly fetch manifest core-js@^3.6.5
27 http fetch GET 304 https://registry.npmjs.org/core-js 252ms (from cache)
28 silly fetch manifest prettier@^2.1.2
29 http fetch GET 304 https://registry.npmjs.org/prettier 67ms (from cache)
30 silly fetch manifest prettier-eslint@^11.0.0
31 http fetch GET 304 https://registry.npmjs.org/prettier-eslint 99ms (from cache)
32 silly fetch manifest prettier-stylelint@^0.4.2
33 http fetch GET 304 https://registry.npmjs.org/prettier-stylelint 67ms (from cache)
34 silly fetch manifest prettier-tslint@^0.4.2
35 http fetch GET 304 https://registry.npmjs.org/prettier-tslint 70ms (from cache)
36 timing idealTree Completed in 593ms
37 timing command:install Completed in 595ms
38 verbose stack Error: unable to resolve dependency tree
38 verbose stack     at Arborist.[failPeerConflict] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1061:25)
38 verbose stack     at Arborist.[loadPeerSet] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1041:36)
38 verbose stack     at async Arborist.[buildDepStep] (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:796:11)
38 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:209:7)
38 verbose stack     at async Promise.all (index 1)
38 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:123:5)
38 verbose stack     at async install (C:\Program Files\nodejs\node_modules\npm\lib\install.js:38:3)
39 verbose cwd <MYPATH>\AppData\Local\Temp\coc-prettier-mfWmq1
40 verbose Windows_NT 10.0.18363
41 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--ignore-scripts" "--no-lockfile" "--production"
42 verbose node v15.5.1
43 verbose npm  v7.3.0
44 error code ERESOLVE
45 error ERESOLVE unable to resolve dependency tree
46 error
47 error While resolving: coc-prettier@1.1.20
47 error Found: prettier@2.2.1
47 error node_modules/prettier
47 error   prettier@"^2.1.2" from the root project
47 error
47 error Could not resolve dependency:
47 error peer prettier@"^1.7.4" from prettier-tslint@0.4.2
47 error node_modules/prettier-tslint
47 error   prettier-tslint@"^0.4.2" from the root project
47 error
47 error Fix the upstream dependency conflict, or retry
47 error this command with --force, or --legacy-peer-deps
47 error to accept an incorrect (and potentially broken) dependency resolution.
47 error
47 error See <MYPATH>\Local\npm-cache\eresolve-report.txt for a full report.
48 verbose exit 1
```
</details>

**Comment by andyliuhaowen** [comment]
I can reproduce this on Windows.

**Comment by chemzqm** [comment]
Upgrade your coc.nvim.
